services:
  backend:
    image: yagohfa/prostudy-backend:latest
    build: ./prostudy-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
    depends_on:
      - db

  frontend:
    build: ./PlanBTech
    ports:
      - "4200:4200"
    depends_on:
      - backend

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: meu_banco
    ports:
      - "3306:3306"