# Usa uma imagem Node para construir a aplicação
FROM node:18 AS build

# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos necessários para o build
COPY . .

# Instala as dependências
RUN npm install

# Roda o build de produção
RUN npm run prod

# Usa uma imagem Node mais leve para rodar o servidor
FROM node:18-slim

# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos do build anterior para o container final
COPY --from=build /app/dist /app

# Expõe a porta que o servidor utiliza
EXPOSE 4200

# Comando para iniciar o servidor
CMD ["node", "plan-btec/server/server.mjs"]
