spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:db}:3306/meu_banco
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: planbtechnology59@gmail.com
    password: ${Senha_Email}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        ssl:
          trust: smtp.gmail.com
api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}