spring:
  datasource:
    url: jdbc:h2:mem:homdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: always
    data: import.sql
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: planbtechnology59@gmail.com
    password: ${Email_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        ssl:
          trust: smtp.gmail.com
api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}